clusterName: homelab
talosVersion: v1.14.1
kubernetesVersion: v1.36.3
endpoint: https://192.168.99.9:6443

clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
domain: cluster.local

cniConfig:
  name: none

additionalApiServerCertSans:
  - 192.168.99.9
  - 127.0.0.1
additionalMachineCertSans:
  - 192.168.99.9

nodes:
  - hostname: cp-1
    ipAddress: 192.168.99.21
    controlPlane: true
    nameservers: [192.168.99.1, 1.1.1.1]
    installDiskSelector:
      size: ">= 50GB"
    networkInterfaces:
      - interface: ens18
        dhcp: true
        vip:
          ip: 192.168.99.9

  - hostname: cp-2
    ipAddress: 192.168.99.22
    controlPlane: true
    nameservers: [192.168.99.1, 1.1.1.1]
    installDiskSelector:
      size: ">= 50GB"
    networkInterfaces:
      - interface: ens18
        dhcp: true
        vip:
          ip: 192.168.99.9

  - hostname: cp-3
    ipAddress: 192.168.99.23
    controlPlane: true
    nameservers: [192.168.99.1, 1.1.1.1]
    installDiskSelector:
      size: ">= 50GB"
    networkInterfaces:
      - interface: ens18
        dhcp: true
        vip:
          ip: 192.168.99.9

  - hostname: worker-1
    ipAddress: 192.168.99.31
    controlPlane: false
    nameservers: [192.168.99.1, 1.1.1.1]
    installDiskSelector:
      size: ">= 100GB"

  - hostname: worker-2
    ipAddress: 192.168.99.32
    controlPlane: false
    nameservers: [192.168.99.1, 1.1.1.1]
    installDiskSelector:
      size: ">= 100GB"

patches:
  - "@./patches/common.yaml"

controlPlane:
  patches:
    - "@./patches/controlplane.yaml"

worker:
  patches:
    - "@./patches/worker.yaml"